### ISSUE TITLE
TypeError: write only attribute

### ISSUE THREAD

**Issue by securitynoob** [securityMB/burp-exceptions#2]
Hey,

I am building a Burp extension. I have gone through your burp-exceptions setup. Looks like I ran into a problem. ` 
Traceback (most recent call last):
  File "C:\Users\xyz\Downloads\extender.py", line 65, in <module>
    FixBurpExceptions()
  File "C:\Users\xyz\Documents\modules\exceptions_fix.py", line 22, in FixBurpExceptions
    FixBurpExceptionsForClass(cls)
  File "C:\Users\xyz\Documents\modules\exceptions_fix.py", line 16, in FixBurpExceptionsForClass
    for name, method in inspect.getmembers(cls, inspect.ismethod):
  File "C:\Users\xyz\Downloads\jython-standalone-2.7.0.jar\Lib\inspect.py", line 257, in getmembers
  File "C:\Users\xyz\Downloads\jython-standalone-2.7.0.jar\Lib\inspect.py", line 257, in getmembers
TypeError: write only attribute

	at org.python.core.Py.TypeError(Py.java:259)
	at org.python.core.PyBeanEvent._doget(PyBeanEvent.java:22)
	at org.python.core.PyObject._doget(PyObject.java:1155)
	at org.python.core.PyObject.__get__(PyObject.java:3798)
	at org.python.core.PyType.type___findattr_ex__(PyType.java:1511)
	at org.python.core.PyType.__findattr_ex__(PyType.java:1490)
	at org.python.core.__builtin__.getattr(__builtin__.java:633)
	at org.python.core.__builtin__.getattr(__builtin__.java:624)
	at org.python.core.BuiltinFunctions.__call__(__builtin__.java:149)
	at org.python.core.PyObject.__call__(PyObject.java:482)
	at inspect$py.getmembers$19(C:\Users\xyz\Downloads\jython-standalone-2.7.0.jar\Lib\inspect.py:263)
	at inspect$py.call_function(C:\Users\xyz\Downloads\jython-standalone-2.7.0.jar\Lib\inspect.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:153)
	at org.python.core.PyFunction.__call__(PyFunction.java:423)
	at exceptions_fix$py.FixBurpExceptionsForClass$3(C:\Users\xyz\Documents\modules\exceptions_fix.py:18)
	at exceptions_fix$py.call_function(C:\Users\xyz\Documents\modules\exceptions_fix.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at exceptions_fix$py.FixBurpExceptions$4(C:\Users\xyz\Documents\modules\exceptions_fix.py:21)
	at exceptions_fix$py.call_function(C:\Users\xyz\Documents\modules\exceptions_fix.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:124)
	at org.python.core.PyFunction.__call__(PyFunction.java:403)
	at org.python.pycode._pyx5.f$0(C:\Users\xyz\Downloads\extender.py:65)
	at org.python.pycode._pyx5.call_function(C:\Users\xyz\Downloads\extender.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at burp.a9m.<init>(Unknown Source)
	at burp.d5t.a(Unknown Source)
	at burp.aib.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
`
Please could you let me know what is the issue? Thanks!

**Comment by rewardone** [comment]
I think this is "normal" behavior as described [here](https://sourceforge.net/p/jython/mailman/jython-users/thread/f5f747f10708210857j68e20735sac74eeff354b08f5%40mail.gmail.com/#msg13215685)

However, that doesn't mean we can't be more verbose and gain additional control over the logging here. 

My particular issue with this arose over the javax.swing.JMenuItem class. I've patched my code with the following for now. I surrounded the for in a try/catch. I specifically except TypeError and specifically pass it if javax.swing classes are detected. Otherwise, we raise the error and get more specific information in regards to what exactly failed. 

```
def FixBurpExceptionsForClass(cls):
    try:
        for name, method in inspect.getmembers(cls, inspect.ismethod):
            setattr(cls, name, decorate_function(method))
    except TypeError as err:
        if "javax.swing" in repr(cls):
            # This is "correct" and we can't getmembers on these
            pass
        else:
            print("cls:" + repr(cls))
            print("ismethod:" + inspect.ismethod.__name__)
            print("exception: %s" % sys.exc_info()[0])
            raise
    except:
        print("cls:" + repr(cls))
        print("ismethod:" + inspect.ismethod.__name__)
        print("exception: %s" % sys.exc_info()[0])
        raise
    return cls
